// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $AppRouter from "./routes/AppRouter.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_players from "./routes/api/players.ts";
import * as $game_screen from "./routes/game-screen.tsx";
import * as $game from "./routes/game.tsx";
import * as $game_GameRouter from "./routes/game/GameRouter.tsx";
import * as $game_create_game from "./routes/game/create-game.tsx";
import * as $game_modify_game from "./routes/game/modify-game.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $player from "./routes/player.tsx";
import * as $team from "./routes/team.tsx";
import * as $Main from "./islands/Main.tsx";
import * as $PlayerTest from "./islands/PlayerTest.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/AppRouter.tsx": $AppRouter,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/players.ts": $api_players,
    "./routes/game-screen.tsx": $game_screen,
    "./routes/game.tsx": $game,
    "./routes/game/GameRouter.tsx": $game_GameRouter,
    "./routes/game/create-game.tsx": $game_create_game,
    "./routes/game/modify-game.tsx": $game_modify_game,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/player.tsx": $player,
    "./routes/team.tsx": $team,
  },
  islands: {
    "./islands/Main.tsx": $Main,
    "./islands/PlayerTest.tsx": $PlayerTest,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
